title: ~jason
description: !

url: https://jdenalil.github.io

remote_theme: riggaz/no-style-please

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: :compressed
